'use client';

import {useCallback,useEffect,useRef,useState, type FormEvent} from 'react';
import {Bell,Plus,Ticket,History,Settings,ArrowUpRight,RefreshCw,Pause,Play,Pencil,Trash2,Check,Radio,ChevronRight,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {api,ApiError,CHAINS,today,type Chain,type CinemaAlert,type Theater,type CheckResult,type HistoryItem} from './api';

const chainKeys=Object.keys(CHAINS) as Chain[];
type Draft=Omit<CinemaAlert,'id'|'createdAt'>;
const blank=():Draft=>({chain:'cgv',movieTitle:'',theaterId:null,theaterName:'',date:today(),format:'일반관',enabled:true});
const timeLabel=(value:string)=>new Date(value).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
export default function Home(){
 const [alerts,setAlerts]=useState<CinemaAlert[]>([]),[history,setHistory]=useState<HistoryItem[]>([]),[tab,setTab]=useState('alerts'),[filter,setFilter]=useState<Chain|'all'>('all');
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[auth,setAuth]=useState(false),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[checking,setChecking]=useState(false);
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState<Draft>(blank),[formError,setFormError]=useState('');
 const [theaters,setTheaters]=useState<Theater[]>([]),[theaterLoading,setTheaterLoading]=useState(false),[theaterMessage,setTheaterMessage]=useState('');
 const [deleting,setDeleting]=useState<CinemaAlert|null>(null),[results,setResults]=useState<Record<string,CheckResult>>({}),[permission,setPermission]=useState('default');
 const inFlight=useRef(false),seen=useRef(new Set<string>());
 const fail=useCallback((e:unknown)=>{setError(e instanceof Error?e.message:'연결을 확인해 주세요.');if(e instanceof ApiError&&e.status===401)setAuth(true)},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [a,h]=await Promise.all([api<{alerts:CinemaAlert[]}>('/api/alerts'),api<{notifications:HistoryItem[]}>('/api/history')]);setAlerts(a.alerts);setHistory(h.notifications);seen.current=new Set(h.notifications.map(n=>n.id));setAuth(false)}catch(e){fail(e)}finally{setLoading(false)}},[fail]);
 useEffect(()=>{void load();setPermission('Notification' in window?Notification.permission:'unsupported')},[load]);
 const checkNow=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;setChecking(true);try{const data=await api<{results:CheckResult[];notifications:HistoryItem[]}>('/api/check','POST',{});setResults(old=>({...old,...Object.fromEntries(data.results.map(r=>[r.alertId,r]))}));for(const item of data.notifications||[]){if(!seen.current.has(item.id)){seen.current.add(item.id);if('Notification' in window&&Notification.permission==='granted'){try{new Notification(item.title||'예매 오픈 알림',{body:item.message||'새로운 상영 일정이 확인됐어요.'})}catch{/* Mobile platforms may require service workers. In-app history remains available. */}}}}const h=await api<{notifications:HistoryItem[]}>('/api/history');setHistory(h.notifications);setNotice(data.results.length?'확인을 마쳤어요. 알림별 확인 상태를 확인해 주세요.':'확인할 활성 알림이 없어요.')}catch(e){fail(e)}finally{inFlight.current=false;setChecking(false)}},[fail]);
 useEffect(()=>{if(!alerts.some(a=>a.enabled))return;const id=window.setInterval(()=>{if(document.visibilityState==='visible')void checkNow()},60000);return()=>window.clearInterval(id)},[alerts,checkNow]);
 useEffect(()=>{if(!open)return;let live=true;setTheaterLoading(true);setTheaters([]);setTheaterMessage('');api<{theaters:Theater[];status:string;message?:string}>(`/api/theaters?chain=${draft.chain}`).then(data=>{if(live){setTheaters(data.theaters);setTheaterMessage(data.message||'')}}).catch(e=>{if(live)setTheaterMessage(e instanceof Error?e.message:'극장 목록을 불러오지 못했어요.')}).finally(()=>{if(live)setTheaterLoading(false)});return()=>{live=false}},[open,draft.chain]);
 function newAlert(){setEditing(null);setDraft(blank());setFormError('');setOpen(true)}
 function editAlert(a:CinemaAlert){setEditing(a.id);setDraft({...a});setFormError('');setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setFormError('');try{const data=await api<{alert:CinemaAlert}>(editing?`/api/alerts/${editing}`:'/api/alerts',editing?'PATCH':'POST',draft);setAlerts(old=>editing?old.map(a=>a.id===editing?data.alert:a):[data.alert,...old]);setOpen(false);setNotice(editing?'알림 조건을 수정했어요.':'새 알림을 등록했어요.')}catch(e){setFormError(e instanceof Error?e.message:'저장하지 못했어요.');if(e instanceof ApiError&&e.status===401)setAuth(true)}finally{setBusy(false)}}
 async function toggle(a:CinemaAlert){setBusy(true);try{const data=await api<{alert:CinemaAlert}>(`/api/alerts/${a.id}`,'PATCH',{enabled:!a.enabled});setAlerts(old=>old.map(x=>x.id===a.id?data.alert:x));setNotice(a.enabled?'알림을 잠시 멈췄어요.':'알림을 다시 시작했어요.')}catch(e){fail(e)}finally{setBusy(false)}}
 async function remove(){if(!deleting)return;setBusy(true);try{await api(`/api/alerts/${deleting.id}`,'DELETE');setAlerts(old=>old.filter(a=>a.id!==deleting.id));setDeleting(null);setNotice('알림을 삭제했어요.')}catch(e){fail(e)}finally{setBusy(false)}}
 async function requestPermission(){if(!('Notification' in window)){setPermission('unsupported');return}try{setPermission(await Notification.requestPermission())}catch{setNotice('이 브라우저에서는 알림 권한을 요청할 수 없어요.')}}
 const visible=alerts.filter(a=>filter==='all'||a.chain===filter);
 return <div className="first-seat"><header className="site-header"><a className="brand" href="/" aria-label="첫자리 홈"><span className="brand-icon"><Ticket size={23}/></span><span>첫자리<small>FIRST SEAT</small></span></a><button className="icon-button" aria-label="알림 설정" onClick={()=>setTab('settings')}><Bell size={21}/></button></header>
 <main className="main-shell"><div className="page-heading"><div><h1>{tab==='alerts'?'내 알림':tab==='history'?'알림 기록':'설정'}{tab==='alerts'&&<span className="count">{alerts.length.toString().padStart(2,'0')}</span>}</h1></div>{tab==='alerts'&&<button className="primary" onClick={newAlert}><Plus size={19}/>새 알림</button>}</div>
 {error&&<div className="error-box" role="alert">{error} {auth?<a href="/signin-with-chatgpt?return_to=%2F">로그인하고 계속하기 <ArrowRight size={15}/></a>:<button onClick={()=>void load()}>다시 시도</button>}</div>}
 {notice&&<div className="notice" role="status">{notice}<button aria-label="안내 닫기" onClick={()=>setNotice('')}>×</button></div>}
 {tab==='alerts'&&<><section className="monitor-banner"><span className="live-dot"/><div><strong>앱을 열어 둔 동안 확인해요</strong><p>활성 알림을 1분마다 확인합니다. 화면을 닫으면 확인이 멈춰요.</p></div><button onClick={()=>void checkNow()} disabled={checking||!alerts.some(a=>a.enabled)}><RefreshCw size={16} className={checking?'spin':''}/>{checking?'확인 중':'지금 확인'}</button></section><div className="filter-bar" aria-label="영화관 필터"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>전체 <span>{alerts.length}</span></button>{chainKeys.map(chain=><button key={chain} className={filter===chain?'selected':''} onClick={()=>setFilter(chain)}>{CHAINS[chain].name}</button>)}</div>
 <div className="list-heading"><span>기다리는 상영</span><small>{visible.length}개의 알림</small></div>
 {loading?<div className="empty-state"><RefreshCw className="spin"/><p>알림을 불러오는 중이에요.</p></div>:visible.length===0?<section className="empty-state"><div className="empty-ticket"><Ticket size={42}/><span className="ticket-stars">✦</span></div><h2>{alerts.length?'이 영화관의 알림이 없어요':'다음 영화의 첫자리를 만나세요'}</h2><p>영화와 극장, 원하는 날짜를 골라 주세요.<br/>예매가 열리는 순간을 함께 기다릴게요.</p><button className="primary" onClick={newAlert}><Plus size={18}/>첫 알림 등록하기</button><div className="empty-chains">CGV <i/> 롯데시네마 <i/> 메가박스</div></section>:<div className="ticket-list">{visible.map((a,index)=><article className={`alert-ticket ${!a.enabled?'paused':''}`} key={a.id}><div className="ticket-main"><div className="ticket-top"><span className={`chain-tag ${a.chain}`}>{CHAINS[a.chain].name}</span><span className={`state-tag ${a.enabled?'':'off'}`}><span/>{a.enabled?'확인 대기':'일시 중지'}</span></div><h2>{a.movieTitle}</h2><p className="theater-name">{a.theaterName} <span>·</span> {a.format}</p><div className="ticket-date"><span>관람일</span><strong>{a.date.replaceAll('-','. ')}</strong></div><div className="check-status">{results[a.id]?<><Radio size={14}/><span>{results[a.id].message}<small>{timeLabel(results[a.id].checkedAt)} 확인</small></span></>:<><Radio size={14}/><span>{a.chain==='cgv'?'CGV 자동 확인 연동 준비 중':!a.theaterId?'극장 목록에서 선택하면 자동 확인할 수 있어요':'예매 오픈 여부를 확인할 준비가 됐어요'}</span></>}</div>{results[a.id]?.showtimes?.length>0&&<div className="showtimes">{results[a.id].showtimes.map((s,i)=><span key={i}>{s.startTime||s.time||'상영 일정'} {s.screenName}</span>)}</div>}</div><div className="ticket-stub"><span className="ticket-number">NO. {String(index+1).padStart(3,'0')}</span><a className="booking-link" href={CHAINS[a.chain].url} target="_blank" rel="noreferrer">예매 페이지 <ArrowUpRight size={17}/></a><div className="ticket-actions"><button disabled={busy} onClick={()=>void toggle(a)} aria-label={`${a.movieTitle} ${a.enabled?'일시 중지':'다시 시작'}`} title={a.enabled?'일시 중지':'다시 시작'}>{a.enabled?<Pause size={17}/>:<Play size={17}/>}</button><button onClick={()=>editAlert(a)} aria-label={`${a.movieTitle} 수정`} title="수정"><Pencil size={17}/></button><button onClick={()=>setDeleting(a)} aria-label={`${a.movieTitle} 삭제`} title="삭제"><Trash2 size={17}/></button></div></div></article>)}</div>}
 <aside className="help-row"><span>알아두면 좋아요</span><p>상영 일정이 확인되면 알려드려요. 좌석 확보와 예매는 영화관에서 진행해 주세요.</p><ArrowUpRight size={18}/></aside></>}
 {tab==='history'&&<section className="history-list">{history.length?history.map(n=><article className="history-item" key={n.id}><span className="history-icon"><Bell size={21}/></span><div><h2>{n.title||'예매 오픈 소식'}</h2><p>{n.message||'새 상영 일정이 확인됐어요.'}</p><small>{timeLabel(n.createdAt)}</small></div></article>):<div className="empty-state"><History size={36}/><h2>아직 도착한 소식이 없어요</h2><p>등록한 조건의 상영이 확인되면<br/>이곳에 알림 기록이 남아요.</p><button className="secondary" onClick={()=>setTab('alerts')}>내 알림 보기<ChevronRight size={17}/></button></div>}</section>}
 {tab==='settings'&&<section className="settings-list"><div className="setting-card"><div className="setting-label"><Bell size={22}/><h2>브라우저 알림</h2><span className="permission-tag">{permission==='granted'?'허용됨':permission==='denied'?'차단됨':permission==='unsupported'?'지원 안 됨':'권한 필요'}</span></div><p>앱을 열어 둔 동안 새 소식을 기기 알림으로도 받아요. 브라우저에 따라 기기 알림이 지원되지 않을 수 있어요.</p>{permission==='denied'?<p className="muted">브라우저의 사이트 설정에서 알림을 허용해 주세요.</p>:permission==='unsupported'?<p className="muted">이 브라우저에서는 앱 안의 알림 기록을 확인해 주세요.</p>:permission!=='granted'?<button className="primary" onClick={()=>void requestPermission()}>알림 허용하기</button>:<button className="secondary" onClick={()=>{try{new Notification('첫자리 테스트 알림',{body:'기기 알림이 잘 도착했어요. 실제 예매 오픈 알림이 아닙니다.'});setNotice('테스트 알림을 보냈어요. 실제 예매 오픈 알림이 아닙니다.')}catch{setNotice('이 브라우저에서는 기기 알림을 보낼 수 없어요. 앱의 알림 기록을 이용해 주세요.')}}}><Check size={16}/>테스트 알림 보내기</button>}</div><div className="setting-card"><h2>확인 방식 안내</h2><p>화면이 보이는 동안 1분마다 확인합니다. 앱을 닫거나 다른 앱으로 이동하면 자동 확인이 멈춰요. 백그라운드 푸시는 지원하지 않습니다.</p><div className="integration-row"><span>CGV</span><small>자동 확인 연동 준비 중</small></div><div className="integration-row"><span>롯데시네마 · 메가박스</span><small>연결된 극장 일정 확인</small></div><p className="muted">영화관 응답과 상영 정보에 따라 확인이 지연되거나 실패할 수 있어요.</p></div></section>}
 <footer className="desktop-footer"><span>FIRST SEAT</span><p>설레는 기다림에, 첫자리.</p></footer></main>
 <nav className="bottom-nav" aria-label="주 메뉴">{[{key:'alerts',label:'내 알림',Icon:Ticket},{key:'history',label:'알림 기록',Icon:History},{key:'settings',label:'설정',Icon:Settings}].map(({key,label,Icon})=><button key={key} className={tab===key?'active':''} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setNotice('')}}><Icon size={21}/><span>{label}</span></button>)}</nav>
 <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value)}}><DialogContent className="alert-sheet"><DialogTitle>{editing?'알림 수정':'새 알림 등록'}</DialogTitle><DialogDescription>기다리는 영화의 조건을 알려 주세요.</DialogDescription><form onSubmit={save} className="alert-form"><fieldset><legend>영화관</legend><div className="chain-selector">{chainKeys.map(chain=><button type="button" key={chain} className={draft.chain===chain?'selected':''} onClick={()=>setDraft(d=>({...d,chain,theaterId:null,theaterName:'',format:CHAINS[chain].formats[0],regionCode:undefined,regionDetailCode:undefined}))}>{CHAINS[chain].name}</button>)}</div></fieldset><label>영화 제목<input required maxLength={120} placeholder="정확한 영화 제목을 입력해 주세요" value={draft.movieTitle} onChange={e=>setDraft(d=>({...d,movieTitle:e.target.value}))}/></label><label>지점{theaters.length?<select required value={draft.theaterId||''} onChange={e=>{const t=theaters.find(t=>t.id===e.target.value);setDraft(d=>({...d,theaterId:t?.id||null,theaterName:t?.name||'',regionCode:t?.regionCode,regionDetailCode:t?.regionDetailCode}))}}><option value="">극장을 선택해 주세요</option>{theaters.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>:<select required disabled={theaterLoading||!theaters.length} value={draft.theaterId||''} onChange={e=>{const t=theaters.find(t=>t.id===e.target.value);setDraft(d=>({...d,theaterId:t?.id||null,theaterName:t?.name||'',regionCode:t?.regionCode,regionDetailCode:t?.regionDetailCode}))}}><option value="">{theaterLoading?'지점 목록을 불러오는 중':'지점을 선택해 주세요'}</option>{theaters.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>}</label>{(theaterMessage||(!theaters.length&&!theaterLoading))&&<p className="field-note">{theaterMessage||'선택 가능한 지점 목록이 없습니다.'}</p>}<div className="form-grid"><label>관람 날짜<input type="date" required min={today()} value={draft.date} onChange={e=>setDraft(d=>({...d,date:e.target.value}))}/></label><label>상영관<select value={draft.format} onChange={e=>setDraft(d=>({...d,format:e.target.value}))}>{CHAINS[draft.chain].formats.map(f=><option key={f}>{f}</option>)}</select></label></div>{draft.chain==='cgv'&&<p className="field-note">CGV는 조건을 저장할 수 있어요. 자동 확인은 연동 준비 중입니다.</p>}{formError&&<p className="form-error" role="alert">{formError}</p>}{auth&&<a href="/signin-with-chatgpt?return_to=%2F">로그인하고 계속하기</a>}<button className="primary submit-button" disabled={busy||theaterLoading}>{busy?'저장 중…':editing?'변경 사항 저장':'알림 등록하기'}<ArrowRight size={18}/></button></form></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={value=>{if(!value&&!busy)setDeleting(null)}}><AlertDialogContent className="delete-dialog"><AlertDialogTitle>이 알림을 삭제할까요?</AlertDialogTitle><AlertDialogDescription>{deleting?.movieTitle}의 알림 조건이 삭제됩니다. 다시 받으려면 새로 등록해 주세요.</AlertDialogDescription><div className="dialog-actions"><AlertDialogCancel disabled={busy}>취소</AlertDialogCancel><button className="danger" disabled={busy} onClick={()=>void remove()}>{busy?'삭제 중…':'삭제하기'}</button></div></AlertDialogContent></AlertDialog>
 </div>;
}
